# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@master

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm ci

    - run: npm run build

    # Runs a set of commands using the runners shell
    - name: S3 Upload
      uses: koraykoska/s3-upload-github-action@0.1.3
      env:
        FILE: ./www/
        S3_ENDPOINT: 's3://dynamic-form-demo.softwarecradft.co.za'
        S3_BUCKET: ${{ secrets.S3_BUCKET }}
        S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESSKEY }}
        S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET }}

